name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Set up Git
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Display Tag
      run: echo "Tag pushed, ${{ github.ref }}"

    - name: Extract Tag Name
      run: echo "Tag name is $(basename ${{ github.ref }})"
      id: extract_tag

    - name: Build Docker Image
      run: |
        docker build -t xiao9878/go-beego-admin:$(echo ${{ steps.extract_tag.outputs.TAG }})  .
        docker tag xiao9878/go-beego-admin:$(echo ${{ steps.extract_tag.outputs.TAG }}) xiao9878/go-beego-admin:latest

    - name: Push Docker Image
      run: |
        docker push xiao9878/go-beego-admin:$(echo ${{ steps.extract_tag.outputs.TAG }}) 
        docker push xiao9878/go-beego-admin:latest
