name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker 镜像'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Set up Git
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Extract Tag
      id: extract_tag
      run: echo latest is ':' ${{ github.ref }}

    - name: Build Docker Image
      run: |
        docker build -t xiao9878/go-beego-admin:${{ github.ref }} .
        docker tag xiao9878/go-beego-admin:${{ github.ref }} xiao9878/go-beego-admin:latest

    - name: Push Docker Image
      run: |
        docker push xiao9878/go-beego-admin:${{ github.ref }}
        docker push xiao9878/go-beego-admin:latest
