name: 构建并推送 Docker 镜像

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker 镜像标签'
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v2

    - name: 设置 Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 登录到 Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: 提取标签
      id: extract_tag
      run: echo "::set-output name=TAG::${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') ? github.ref : github.event.inputs.tag }}"

    - name: 构建并推送 Docker 镜像
      run: |
        docker buildx create --use
        docker buildx build -t xiao9878/go-beego-admin:${{ steps.extract_tag.outputs.TAG }} .
        docker push xiao9878/go-beego-admin:${{ steps.extract_tag.outputs.TAG }}
