name: zgpt-web build & push

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Set up Git
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Extract Tag
      id: extract_tag
      run: echo "::set-output name=TAG::${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') ? github.ref : github.event.inputs.tag }}"

    - name: Build Docker Image
      run: |
        docker build -t xiao9878/go-beego-manager:${{ steps.extract_tag.outputs.TAG }} .
        docker tag xiao9878/go-beego-manager:${{ steps.extract_tag.outputs.TAG }} your-dockerhub-username/your-repo-name:latest

    - name: Push Docker Image
      run: |
        docker push your-dockerhub-username/your-repo-name:${{ steps.extract_tag.outputs.TAG }}
        docker push your-dockerhub-username/your-repo-name:latest
